### ISSUE TITLE
Turn Off USB Storage

### ISSUE THREAD

**Issue by sinanilyas** [k1z1lelma/guardian#1]
Cannot use external USB disks after applying "Full Protection". I doubt the option "Turn Off USB Storage" is necessary for home users. Removing from "Full Protection" might be considered.

**Comment by sinanilyas** [comment]
The application definitely must have a "restore" option.

**Comment by k1z1lelma** [comment]
If you want to withdraw the "Turn Off USB Storage" setting, you can do so by entering the following value in regedit:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\USBSTOR]
"Start"=dword:00000003

<img width="454" alt="1" src="https://user-images.githubusercontent.com/70051313/214024639-615e620e-5f58-4de4-9c1e-9a856fc37814.png">

**Comment by k1z1lelma** [comment]
Thank you very much for your feedback. I will make the correction you mentioned and share it as soon as possible.

**Comment by sinanilyas** [comment]
Thank you.

**Comment by k1z1lelma** [comment]
Removed the option to turn off USB storage from the Full privacy tab. You can check.

**Comment by sinanilyas** [comment]
Thank you for your quick response.
